{
 "title": "Bike Stats Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " Total Bikes Available by Provider",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  provider,\r\n  SUM(bike_count) AS \"Total Available Bikes\"\r\nFROM\r\n  bike_stats\r\nGROUP BY\r\n  provider;\r\n"
    }
   ]
  },
  {
   "title": "Available Bikes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp,\r\n  SUM(bike_count) AS total_bikes\r\nFROM\r\n  bike_stats\r\nGROUP BY\r\n  timestamp\r\nORDER BY\r\n  timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Latest Bike Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp,\r\n  provider,\r\n  station_id,\r\n  bike_count\r\nFROM\r\n  bike_stats\r\nORDER BY\r\n  timestamp DESC\r\nLIMIT 100;\r\n"
    }
   ]
  }
 ]
}